spring.application.name=sw_backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sw_multimedia_backend
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail Configuration (Kept the same)
spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.username=swmultimedia2023@gmail.com
spring.mail.password=pcvg lfib aocp svac
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin email
app.admin.email=swmultimedia2023@gmail.com