# spring.application.name=sw_backend

# # PostgreSQL Database Configuration
# spring.datasource.url=jdbc:postgresql://ep-lively-sky-atlo02on.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_BQ1ErDex4Ana
# spring.datasource.driver-class-name=org.postgresql.Driver
# server.port=8082

# # JPA / Hibernate Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.default-encoding=UTF-8
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false


spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000

spring.application.name=sw_backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-lively-sky-atlo02on.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BQ1ErDex4Ana
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#cloudinary
cloudinary.cloud-name=dpkt99r2i
cloudinary.api-key=651524612339676
cloudinary.api-secret=VZE8OjxZn1wvjlLszR-xONluJjo


# Admin email (your Gmail where you want to receive notifications)
app.admin.email=${MAIL_USERNAME}